### ISSUE TITLE
启动时告警，没有检测到任何执行语句

### ISSUE THREAD

**Issue by Cyber-Chaser** [TheKingOfDuck/MySQLMonitor#1]
![image](https://user-images.githubusercontent.com/37996512/54809993-d22ade00-4cbf-11e9-92ee-c40d51f5e1c3.png)
目标数据库是windows环境

**Comment by TheKingOfDuck** [comment]
亲, 这个目前仅支持监控本地数据库喔 , 你可以把这个项目下载到win里面去执行的。（仔细思考了下能否直接用sql查询的方式实现语句监控, 解决你遇到的这类需求, 答案是否, 会涉及到sql读写文件权限的问题, 逻辑上好像是死循环, 即要记录日志到文件, 又要去读日志文件, 这样读的过程又会写到日志文件, 造成死循环,。）

**Comment by aaeolus** [comment]
hello，我这边是监控的本地数据库，也遇到了这个问题，请问怎么解决呢

**Comment by TheKingOfDuck** [comment]
@aaeolus 可以的话麻烦提供一下具体的环境信息，系统版本 python版本 mysql版本 相关错误日志等，能微信私聊最方便了

**Comment by aaeolus** [comment]
windows10系统，python3.7.3，mysql5.7.26
λ python main.py
[11:01:56]配置解析成功...
[11:01:56]数据库连接成功...
[11:01:56]当前数据库版本为: 5.7.26
C:\Users\ysf\AppData\Local\Programs\Python\Python37\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 485")
  result = self._query(query)
[11:01:57]日志状态为:ON
[11:01:57]日志监听中...

-------------------------------------------------------------
会出现2019_10_25_log.txt，但是执行命令没有输出
----------------------------------------------------------------
另外，手动改mysql的配置文件
general_log=1
general_log_file=C:\xxxx\xxx\xxx\mysql.log
然后可以有记录

**Comment by sodmelody** [comment]
无法读取虚拟机mysql log，正常可使用
![image](https://user-images.githubusercontent.com/29257678/67654616-1c2c1e80-f989-11e9-9f8d-de53052852b9.png)

**Comment by TheKingOfDuck** [comment]
@sodmelody 只能读本地mysql的。

**Comment by sodmelody** [comment]
> @sodmelody 只能读本地mysql的。

有没有考虑读取外链数据库？

**Comment by TheKingOfDuck** [comment]
@aaeolus 预计明后天修复，很少用windows系统，所以适配上也没做好

**Comment by TheKingOfDuck** [comment]
> > @sodmelody 只能读本地mysql的。
> 
> 有没有考虑读取外链数据库？

目前有两个问外链数据库的了，会考虑，也就是明后天的事嘛，忙完一并解决了

**Comment by sodmelody** [comment]
> > > @sodmelody 只能读本地mysql的。
> > 
> > 
> > 有没有考虑读取外链数据库？
> 
> 目前有两个问外链数据库的了，会考虑，也就是明后天的事嘛，忙完一并解决了

法师的代码审计辅助那个插件，不知道是那个，可以参考下，他的可以支持外链

**Comment by TheKingOfDuck** [comment]
> > > > @sodmelody 只能读本地mysql的。
> > > 
> > > 
> > > 有没有考虑读取外链数据库？
> > 
> > 
> > 目前有两个问外链数据库的了，会考虑，也就是明后天的事嘛，忙完一并解决了
> 
> 法师的代码审计辅助那个插件，不知道是那个，可以参考下，他的可以支持外链

好的，感谢反馈与提醒

**Comment by aaeolus** [comment]
感谢🙏

**Comment by monitor403** [comment]
![G57%RHHA96SA_$VN`EFP{~L](https://user-images.githubusercontent.com/45124775/74100129-4a172680-4b66-11ea-9f50-f43d3834039e.png)
![1KK`IM{J0Z8X%2F@2L6T}72](https://user-images.githubusercontent.com/45124775/74100130-4be0ea00-4b66-11ea-9da1-33dfc185fe3b.png)
python2 好像数据格式不对，要改下代码，ubantu

**Comment by monitor403** [comment]
![G57%RHHA96SA_$VN`EFP{~L](https://user-images.githubusercontent.com/45124775/74100142-8054a600-4b66-11ea-8f1b-acb6a3a99e47.png)

**Comment by kejaly** [comment]
没有检测到任何执行语句 有可能是Mysql 的日志方式是 TABLE ,而不是FILE ,脚本原理是通过tail -f  general_log_file  来工作的， 如果Mysql 日志方式为 TABLE ,自然就没法检测到执行语句。
 建议增加 检测并且修改Mysql 日志记录方式的功能

**Comment by TheKingOfDuck** [comment]
各位: 已使用Java重构，并修改记录方式为TABLE。具体可下载新版本使用。
