### ISSUE TITLE
无法连接数据库，同时不能自动启动日志功能

### ISSUE THREAD

**Issue by ALEXI7** [TheKingOfDuck/MySQLMonitor#2]
当pymysql的连接语句是`db = pymysql.connect(host=host,port=port,user=user,password=password,db=db_name, charset=charset)`时不能连接数据库，改为`db = conn = pymysql.connect(host='127.0.0.1',port = 3306,user='root',passwd='*******',db ='mysql',charset="utf8")`之后可以连接，尝试直接运行第一条代码显示
<img width="944" alt="issue2" src="https://user-images.githubusercontent.com/35003004/54893510-1e109980-4ef1-11e9-9230-b0834997ab71.png">

当日志功能关闭的时候不能自动开启，显示
![issue](https://user-images.githubusercontent.com/35003004/54893363-5f547980-4ef0-11e9-8cb9-9e6971443403.png)
查看mysql本身日志文件，发现位于`/usr/local/mysql/data/******.log`，修改main.py中的log为上述文件地址之后发现可以正常运行。
![iusse3](https://user-images.githubusercontent.com/35003004/54893621-9ecf9580-4ef1-11e9-8e74-7c71e0e35650.png)

版本：mac10.13.6、Python 3.6.3、mysql8.0.12

**Comment by TheKingOfDuck** [comment]
问题已收到   预估是mysql8.0.x对日志的设置方式不同所致（目前我本人的mysql是5.6 其他版本尚未进行测试）  今天下班后会抽时间修复该问题 感谢反馈  @ALEXI7

**Comment by TheKingOfDuck** [comment]
@ALEXI7 已新增对MacOS环境下对MySQL8.0.X的支持（排查得出是权限问题）
