### ISSUE TITLE
数据库监控时，日志一直重复某几条消息

### ISSUE THREAD

**Issue by shirleyxyli** [TheKingOfDuck/MySQLMonitor#3]
麻烦帮忙看下，下图是启动了监控后的日志，一直显示下面几个语句
怎样才能不重复出现呢
![image](https://user-images.githubusercontent.com/19338744/56201288-259c0c00-6073-11e9-97ed-c89b470a641b.png)

**Comment by TheKingOfDuck** [comment]
这个应该不是程序问题哦，看看是不是你的web程序里有代码反复执行该语句
