### ISSUE TITLE
无法连接数据库,windows10

### ISSUE THREAD

**Issue by Aoyanm** [TheKingOfDuck/MySQLMonitor#4]
关于时间那一块代码,我建议是strftime('[%H:%M:%S]') + "配置解析失败 请检查格式是否正确...")这样的格式,因为一开始为修改的时候运行不起来。
后面修改完监控起来以后
![YY截图20190425224404](https://user-images.githubusercontent.com/34020137/56744851-dad56f00-67ab-11e9-9fd5-4f1492e7b31a.png)
,我测试在mysql运行语句看是否成功被监控,但结果并不理想,为监控到哦

**Comment by TheKingOfDuck** [comment]
我这边抽空再对windows进行一次大调整吧，最近一周都贼忙，没注意看gayhub，抱歉 。

**Comment by TheKingOfDuck** [comment]
@Aoyanm 这边定位到是为了兼容MySQL8.0.X时需要提升权限去读文件 代码顺序错了 win监控不成功就是这个原因导致的 目前已修复 时间那块测试问题不存在 如您这边测试还存在请加我微信TheKingOfGaGaGa 看看错误详情。
