### ISSUE TITLE
ubuntu18.04亲测成功

### ISSUE THREAD

**Issue by corp0ra1** [TheKingOfDuck/MySQLMonitor#5]
![](https://ws3.sinaimg.cn/large/006MpoZqgy1g3bfmga3z9j30mi0e2adf.jpg)

**Comment by TheKingOfDuck** [comment]
这个图看着好难受 以为是网不好没加载出来还特意刷新几下页面 gg

**Comment by corp0ra1** [comment]
[![VEv4Gq.md.jpg](https://s2.ax1x.com/2019/05/26/VEv4Gq.md.jpg)](https://imgchr.com/i/VEv4Gq) 可能是图床的原因把！我只是想表达 该软件在Ubuntu下也可以使用，记得sudo运行即可，不然监听不到

**Comment by TheKingOfDuck** [comment]
感谢使用

![fuckme](https://user-images.githubusercontent.com/27769271/58444007-76019180-8128-11e9-8941-82383b4e023a.png)

**Comment by corp0ra1** [comment]
补充：Ubuntu下因为权限以及mysqld强制编码，会报错：mysql错误：ERROR 29 (HY000): File 'xxx.txt' not found (Errcode: 13)，解决方案参考：http://www.111cn.net/database/mysql/46839.htm。
`一开始只是当个脚本小子，没注意，一直运行的还行，最近为了测试sql的load_file漏洞，改了log文件位置才发现一直以来都以/var/lib/mysql/ubuntu.log为log文件写入位置，而main.py生成的日志文件一直无法写入，但是一直能正常使用.......`

**Comment by corp0ra1** [comment]
同时由于此脚本自动开启了日志记录功能，但是并不会自动关闭，所以导致一定存储空间的浪费
因此希望在main.py，在接受键盘中断之后加上一行`data=execSQL(db, "set global general_log=off;")`最后才执行db.close

**Comment by TheKingOfDuck** [comment]
@corp0ra1 老哥要不你直接pull requests吧 [手动狗头]

**Comment by corp0ra1** [comment]
sorry ，我还不会github的这些操作。。不太敢尝试。。。就是你的main.py的156行的db.close（）之前加上一个语句data=execSQL(db, "set global general_log=off;")。这样就可以达到我用该软件的时候检测log是否打开然后帮忙打开，关闭时候，mysql的log帮我自动关闭了（避免收集太多log导致存储空间的占用）
